


export const ancientToMedevilInfantry = {
  hunters: {
    name: "Hunter",
    attack: 1,
    defense: 1,
    health: 10,
    accuracy: 1,
    attackSpeed: 1,
    load: 10,
    range: 5,
    speed: 10,
    pop: 1,
    move: 2,
    resourceCost: { wood: 10, food: 20, stone: 5 },
    time: 5000,
    age: "ancient",
    upkeep: 1,
    trait: ["none"],
    recruitment: "barracks"
  },

  tracker: {
    name: "Tracker",
    attack: 1,
    defense: 1,
    health: 12,
    accuracy: 2,
    attackSpeed: 1,
    load: 12,
    range: 6,
    speed: 100,
    pop: 1,
    move: 4,
    resourceCost: { wood: 15, food: 25, stone: 5 },
    time: 6000,
    age: "stone",
    upkeep: 1,
    trait: ["scout"],
    recruitment: "barracks"
  },

  warrior: {
    name: "Warrior",
    attack: 4,
    defense: 3,
    health: 20,
    accuracy: 1,
    attackSpeed: 1.1,
    load: 10,
    range: 1,
    speed: 9,
    move: 2,
    pop: 1,
    resourceCost: { wood: 20, food: 40, stone: 15, iron: 5 },
    time: 9000,
    age: "bronze",
    upkeep: 2,
    trait: ["none"],
    recruitment: "barracks"
  },

  spearmen: {
    name: "Spearman",
    attack: 5,
    defense: 4,
    health: 22,
    accuracy: 1,
    attackSpeed: 1,
    load: 12,
    range: 2,
    speed: 8,
    pop: 1,
    move: 2,
    resourceCost: { wood: 25, food: 45, stone: 20, iron: 8 },
    time: 10000,
    age: "bronze",
    upkeep: 2,
    trait: ["anti-cavalry"],
    recruitment: "barracks"
  },

  swordsmen: {
    name: "Swordsman",
    attack: 7,
    defense: 5,
    health: 28,
    accuracy: 1,
    attackSpeed: 1.3,
    load: 10,
    range: 1,
    speed: 8,
    pop: 1,
    move: 2,
    resourceCost: { food: 60, iron: 15 },
    time: 12000,
    age: "medevil",
    upkeep: 3,
    trait: ["none"],
    recruitment: "barracks"
  },

  pikemen: {
    name: "Pikeman",
    attack: 6,
    defense: 6,
    health: 30,
    accuracy: 1,
    attackSpeed: 0.9,
    load: 14,
    range: 3,
    speed: 7,
    pop: 1,
    move: 2,
    resourceCost: { wood: 30, food: 55, iron: 12 },
    time: 13000,
    age: "medevil",
    upkeep: 3,
    trait: ["anti-cavalry"],
    recruitment: "barracks"
  },

  scout: {
    name: "Scout",
    attack: 3,
    deffense: 1,
    health: 14,
    accuracy: 2,
    attackSpeed: 1,
    load: 15,
    range: 4,
    speed: 200,
    pop: 1,
    move: 6,
    resourceCost: { food: 30, wood: 15 },
    time: 6000,
    age: "medevil",
    upkeep: 1,
    trait: ["scout"],
    recruitment: "barracks"
  }
};
